# Generated by Django 2.1.4 on 2018-12-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('kor', models.CharField(max_length=20, verbose_name='Кор. счет')),
                ('number', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Компания')),
            ],
        ),
    ]
