# Generated by Django 2.1.4 on 2018-12-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Банковский счет', 'verbose_name_plural': 'Банковские счета'},
        ),
    ]
