# Generated by Django 2.1.4 on 2018-12-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('company', '0002_auto_20181208_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Покупатель')),
                ('services', models.ManyToManyField(to='catalog.Service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name_plural': 'Счета',
                'verbose_name': 'Счет',
            },
        ),
    ]
