# Generated by Django 2.1.4 on 2018-12-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181208_1446'),
        ('document', '0003_auto_20181208_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='company.Company', verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='company.Company', verbose_name='Покупатель'),
        ),
    ]
