# Generated by Django 2.1.4 on 2018-12-09 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20181208_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deel_date',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата составления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='document.Invoice', verbose_name='Счет'),
        ),
    ]
