# Generated by Django 2.1.4 on 2018-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование компании')),
                ('inn', models.CharField(max_length=10, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('owner', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('accountant', models.CharField(max_length=255, verbose_name='Главный бухгалтер')),
            ],
        ),
    ]
