# Generated by Django 2.1.4 on 2018-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='accountant',
            field=models.CharField(help_text='Отображается в подписи', max_length=255, verbose_name='ФИО главного бухгалтера'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(help_text='Отображается в подписи', max_length=255, verbose_name='ФИО руководителя'),
        ),
    ]
